version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/nginx.Dockerfile
    container_name: myapp-nginx
    ports:
      - "8888:80"
    depends_on:
      - php
      - mysql

  php:
    build:
      context: .
      dockerfile: docker/php/php.Dockerfile
    container_name: myapp-php
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: myapp-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: myapp_db
      MYSQL_USER: myapp_user
      MYSQL_PASSWORD: myapp_password
    ports:
      - "3309:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql

